spring:
  application:    name: gateway-proxy

zuul:  prefix: /api
  ignored-services: '*'
  routes:
    employee-service:
      path: /employees/**
      strip-prefix: false
    department-service:
      path: /departments/**
      strip-prefix: false
    organization-service:
      path: /organizations/**
      strip-prefix: false
      
eureka:
   client:    service-url:
      defaultZone: http://localhost:9001/eureka      