apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: app
          image: tanawit17/discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: eureka.client.service-url.defaultZone
              value: http://localhost:9001/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - port: 9001
      targetPort: 8080
  type: LoadBalancer
