spring:  application:    name: employee-service
  cloud:    config:      override-system-properties: false
      allow-override: true
      override-none: true
  sleuth:    sampler:      probability: 1.0
      
eureka:  client:    service-url:      defaultZone: http://localhost:9001/eureka